name: Publish to PyPI.org
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: python3 -m pip install --upgrade build && python3 -m build

      - name: Unittesting
        run: |
          python3 -m pip install requirements.txt
          pytest tests/
